export const destinations = [
    {
        id: 1,
        name: "Sigiriya",
        slug: "sigiriya",
        location: "Matale District",
        region: "Central",
        interest: "Cultural",
        image: "/images/sigiriya.jpg",
        rating: 4.9,
        description: "Ascend the Lion Rock, an ancient fortress and palace ruin surrounded by extensive gardens and reservoirs.",
        attractions: ["Lion Rock Fortress", "Frescoes", "Mirror Wall", "Water Gardens"],
        bestTime: "January to April",
        price: "$30",
        category: "Historical"
    },
    {
        id: 2,
        name: "Ella",
        slug: "ella",
        location: "Hill Country",
        region: "Central",
        interest: "Nature",
        image: "/images/ella.jpg",
        rating: 4.8,
        description: "A small town in the Badulla District of Uva Province, blessed with some of the most beautiful views you can find in Sri Lanka.",
        attractions: ["Nine Arch Bridge", "Little Adam’s Peak", "Ella Rock", "Ravana Falls"],
        bestTime: "January to March",
        price: "$0",
        category: "Mountains"
    },
    {
        id: 3,
        name: "Galle Fort",
        slug: "galle",
        location: "Galle District",
        region: "South",
        interest: "Cultural",
        image: "/images/galle.jpg",
        rating: 4.7,
        description: "A historical, archaeological and architectural heritage monument, which even after more than 423 years maintains a polished appearance.",
        attractions: ["Lighthouse", "Dutch Reformed Church", "Maritime Museum", "Street Markets"],
        bestTime: "December to April",
        price: "$0",
        category: "Historical"
    },
    {
        id: 4,
        name: "Yala National Park",
        slug: "yala",
        location: "Hambantota",
        region: "South",
        interest: "Wildlife",
        image: "/images/yala.jpg",
        rating: 4.6,
        description: "The second largest national park in Sri Lanka, boasting the highest leopard density in the world.",
        attractions: ["Leopard Safari", "Elephant Viewing", "Bird Watching", "Sithulpawwa Rock Temple"],
        bestTime: "February to June",
        price: "$25",
        category: "Safari"
    },
    {
        id: 5,
        name: "Mirissa",
        slug: "mirissa",
        location: "Matara District",
        region: "South",
        interest: "Beaches",
        image: "/images/mirissa.jpg",
        rating: 4.8,
        description: "A small town on the south coast, famous for its golden sand beaches and whale watching.",
        attractions: ["Coconut Tree Hill", "Parrot Rock", "Whale Watching", "Secret Beach"],
        bestTime: "November to April",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 6,
        name: "Kandy",
        slug: "kandy",
        location: "Central Province",
        region: "Central",
        interest: "Cultural",
        image: "/images/kandy.jpg",
        rating: 4.5,
        description: "The last capital of the ancient kings' era of Sri Lanka, home to the Temple of the Sacred Tooth Relic.",
        attractions: ["Temple of the Tooth", "Peradeniya Botanical Gardens", "Kandy Lake", "Udawattakele Sanctuary"],
        bestTime: "January to April",
        price: "$15",
        category: "Heritage"
    },
    {
        id: 7,
        name: "Trincomalee",
        slug: "trincomalee",
        location: "East Coast",
        region: "East",
        interest: "Beaches",
        image: "/images/mirissa-clear.jpg",
        rating: 4.7,
        description: "A port city on the northeast coast, known for having some of the world's most beautiful natural harbors.",
        attractions: ["Nilaveli Beach", "Pigeon Island", "Koneswaram Temple", "Whale Watching"],
        bestTime: "May to September",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 8,
        name: "Jaffna",
        slug: "jaffna",
        location: "North",
        region: "North",
        interest: "Cultural",
        image: "/images/sigiriya-vibrant.jpg",
        rating: 4.4,
        description: "A vibrant city in the far north of Sri Lanka, known for its unique culture, cuisine, and temples.",
        attractions: ["Nallur Kandaswamy Kovil", "Jaffna Fort", "Casuarina Beach", "Nagadeepa Temple"],
        bestTime: "January to September",
        price: "$0",
        category: "Heritage"
    }
];

export const experiences = [
    {
        id: 1,
        title: "Scenic Kandy to Ella Train",
        category: "Adventure",
        location: "Central Highlands",
        image: "/images/train.jpg",
        price: "$15",
        duration: "7 Hours",
        difficulty: "Easy",
        bestTime: "Year-round",
        description: "The world-famous train journey through misty tea plantations, pine forests, and cascading waterfalls.",
        highlights: ["Demodara Nine Arch Bridge", "Tea Estate Views", "Local Food Vendors"]
    },
    {
        id: 2,
        title: "Traditional Cooking Class",
        category: "Culinary",
        location: "Kandy / Ella",
        image: "/images/cooking.jpg",
        price: "$25",
        duration: "3 Hours",
        difficulty: "Easy",
        bestTime: "Year-round",
        description: "Learn the secrets of Sri Lankan spices. Pick fresh ingredients from a local garden and cook a classic rice and curry meal.",
        highlights: ["Spice Education", "Clay Pot Cooking", "Family-style Dining"]
    },
    {
        id: 3,
        title: "Leopard Safari in Yala",
        category: "Wildlife",
        location: "Yala National Park",
        image: "/images/yala.jpg",
        price: "$85",
        duration: "Half Day",
        difficulty: "Moderate",
        bestTime: "Feb – June",
        description: "A thrilling jeep safari in the park with the highest density of leopards in the world.",
        highlights: ["Leopard Spotting", "Elephant Encounters", "Rugged Terrain"]
    },
    {
        id: 4,
        title: "Surfing in Arugam Bay",
        category: "Adventure",
        location: "East Coast",
        image: "/images/mirissa.jpg",
        price: "$40",
        duration: "2 Hours",
        difficulty: "Moderate",
        bestTime: "May – Sept",
        description: "Ride the epic waves of one of the world's top surfing destinations. Perfect for both beginners and pros.",
        highlights: ["Main Point Break", "Sunset Surf", "Chilled Vibes"]
    },
    {
        id: 5,
        title: "Ayurvedic Wellness Retreat",
        category: "Wellness",
        location: "South Coast",
        image: "/images/spa.jpg",
        price: "$120",
        duration: "Full Day",
        difficulty: "Relaxing",
        bestTime: "Dec – April",
        description: "Detoxify your body and mind with ancient Ayurvedic oil massages and herbal steam baths.",
        highlights: ["Herbal Remedies", "Meditation Sessions", "Holistic Healing"]
    },
    {
        id: 6,
        title: "Sigiriya Ballooning",
        category: "Adventure",
        location: "Dambulla",
        image: "/images/sigiriya.jpg",
        price: "$210",
        duration: "1.5 Hours",
        difficulty: "Easy",
        bestTime: "Nov – April",
        description: "Float over the majestic Sigiriya Rock at dawn, witnessing the island's greens from a unique perspective.",
        highlights: ["Aerial Views", "Sunrise Toast", "Bird's eye sigiriya"]
    },
    {
        id: 7,
        title: "Whale Watching",
        category: "Wildlife",
        location: "Mirissa",
        image: "/images/mirissa-clear.jpg",
        price: "$50",
        duration: "4 Hours",
        difficulty: "Moderate",
        bestTime: "Nov – April",
        description: "Embark on a maritime adventure to see blue whales, sperm whales, and dolphins in their natural habitat.",
        highlights: ["Blue Whales", "Eco-friendly Boats", "Ocean Breeze"]
    },
    {
        id: 8,
        title: "Kandy Esala Perahera",
        category: "Festivals",
        location: "Kandy",
        image: "/images/kandy.jpg",
        price: "$0",
        duration: "Evenings",
        difficulty: "Easy",
        bestTime: "July / August",
        description: "Experience Asia's most grand festival featuring decorated elephants, traditional dancers, and fire-breathers.",
        highlights: ["Sacred Relic Procession", "Cultural Dancers", "Historic Tradition"]
    }
];
