export const destinations = [
    {
        id: 1,
        name: "Hikkaduwa",
        slug: "hikkaduwa",
        location: "Galle District",
        region: "South",
        interest: "Beaches",
        image: "/images/mirissa-beach.jpg",
        rating: 4.4,
        description: "A popular resort town known for its strong surf, coral sanctuary, and vibrant nightlife.",
        attractions: ["Coral Reef", "Turtle Hatchery", "Hikkaduwa Beach"],
        bestTime: "November to April",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 2,
        name: "Arugam Bay",
        slug: "arugam-bay",
        location: "Ampara District",
        region: "East",
        interest: "Beaches",
        image: "/images/hawaii-beach.jpg",
        rating: 4.7,
        description: "A surfer's paradise on the east coast, world-renowned for its point breaks and laid-back vibe.",
        attractions: ["Main Point Break", "Elephant Rock", "Whiskey Point"],
        bestTime: "May to September",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 3,
        name: "Horton Plains",
        slug: "horton-plains",
        location: "Nuwara Eliya",
        region: "Central",
        interest: "Nature",
        image: "/images/nature.jpg",
        rating: 4.6,
        description: "A protected area in the central highlands covered by montane grassland and cloud forest.",
        attractions: ["World's End", "Baker's Falls", "Mini World's End"],
        bestTime: "January to March",
        price: "$15",
        category: "Nature"
    },
    {
        id: 4,
        name: "Sigiriya",
        slug: "sigiriya",
        location: "Matale District",
        region: "Central",
        interest: "Cultural",
        image: "/images/sigiriya-vibrant.jpg",
        rating: 4.9,
        description: "Ascend the Lion Rock, an ancient fortress and palace ruin surrounded by extensive gardens and reservoirs.",
        attractions: ["Lion Rock Fortress", "Frescoes", "Mirror Wall", "Water Gardens"],
        bestTime: "January to April",
        price: "$30",
        category: "Historical"
    },
    {
        id: 5,
        name: "Ella",
        slug: "ella",
        location: "Hill Country",
        region: "Central",
        interest: "Nature",
        image: "/images/nine-arch-bridge.jpg",
        rating: 4.8,
        description: "A small town in the Badulla District of Uva Province, blessed with some of the most beautiful views you can find in Sri Lanka.",
        attractions: ["Nine Arch Bridge", "Little Adam’s Peak", "Ella Rock", "Ravana Falls"],
        bestTime: "January to March",
        price: "$0",
        category: "Mountains"
    },
    {
        id: 6,
        name: "Galle Fort",
        slug: "galle",
        location: "Galle District",
        region: "South",
        interest: "Cultural",
        image: "/images/galle.jpg",
        rating: 4.7,
        description: "A historical, archaeological and architectural heritage monument, which even after more than 423 years maintains a polished appearance.",
        attractions: ["Lighthouse", "Dutch Reformed Church", "Maritime Museum", "Street Markets"],
        bestTime: "December to April",
        price: "$0",
        category: "Historical"
    },
    {
        id: 7,
        name: "Yala National Park",
        slug: "yala",
        location: "Hambantota",
        region: "South",
        interest: "Wildlife",
        image: "/images/yala.jpg",
        rating: 4.6,
        description: "The second largest national park in Sri Lanka, boasting the highest leopard density in the world.",
        attractions: ["Leopard Safari", "Elephant Viewing", "Bird Watching", "Sithulpawwa Rock Temple"],
        bestTime: "February to June",
        price: "$25",
        category: "Safari"
    },
    {
        id: 8,
        name: "Mirissa",
        slug: "mirissa",
        location: "Matara District",
        region: "South",
        interest: "Beaches",
        image: "/images/mirissa-beach.jpg",
        rating: 4.8,
        description: "A small town on the south coast, famous for its golden sand beaches and whale watching.",
        attractions: ["Coconut Tree Hill", "Parrot Rock", "Whale Watching", "Secret Beach"],
        bestTime: "November to April",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 9,
        name: "Kandy",
        slug: "kandy",
        location: "Central Province",
        region: "Central",
        interest: "Cultural",
        image: "/images/buddha.png",
        rating: 4.5,
        description: "The last capital of the ancient kings' era of Sri Lanka, home to the Temple of the Sacred Tooth Relic.",
        attractions: ["Temple of the Tooth", "Peradeniya Botanical Gardens", "Kandy Lake", "Udawattakele Sanctuary"],
        bestTime: "January to April",
        price: "$15",
        category: "Heritage"
    },
    {
        id: 10,
        name: "Trincomalee",
        slug: "trincomalee",
        location: "East Coast",
        region: "East",
        interest: "Beaches",
        image: "/images/beach.jpg",
        rating: 4.7,
        description: "A port city on the northeast coast, known for having some of the world's most beautiful natural harbors.",
        attractions: ["Nilaveli Beach", "Pigeon Island", "Koneswaram Temple", "Whale Watching"],
        bestTime: "May to September",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 11,
        name: "Jaffna",
        slug: "jaffna",
        location: "North",
        region: "North",
        interest: "Cultural",
        image: "/images/colombo_line.jpg",
        rating: 4.4,
        description: "A vibrant city in the far north of Sri Lanka, known for its unique culture, cuisine, and temples.",
        attractions: ["Nallur Kandaswamy Kovil", "Jaffna Fort", "Casuarina Beach", "Nagadeepa Temple"],
        bestTime: "January to September",
        price: "$0",
        category: "Heritage"
    },
    {
        id: 12,
        name: "Anuradhapura",
        slug: "anuradhapura",
        location: "North Central",
        region: "North Central",
        interest: "Cultural",
        image: "/images/sigiriya-clear.jpg",
        rating: 4.8,
        description: "The first capital of Sri Lanka, a UNESCO World Heritage site filled with ancient stupas and ruins.",
        attractions: ["Ruwanwelisaya", "Jaya Sri Maha Bodhi", "Isurumuniya"],
        bestTime: "April to September",
        price: "$25",
        category: "Historical"
    },
    {
        id: 13,
        name: "Polonnaruwa",
        slug: "polonnaruwa",
        location: "North Central",
        region: "North Central",
        interest: "Cultural",
        image: "/images/sigiriya.jpg",
        rating: 4.7,
        description: "The second ancient capital, features well-preserved ruins of a royal city from the 11th century.",
        attractions: ["Gal Vihara", "Royal Palace", "Parakrama Samudra"],
        bestTime: "May to July",
        price: "$25",
        category: "Historical"
    },
    {
        id: 14,
        name: "Nuwara Eliya",
        slug: "nuwara-eliya",
        location: "Hill Country",
        region: "Central",
        interest: "Nature",
        image: "/images/tea.png",
        rating: 4.6,
    },
    {
        id: 15,
        name: "Bentota",
        slug: "bentota",
        location: "Galle District",
        region: "South",
        interest: "Beaches",
        image: "/images/mirissa-clear.jpg",
        rating: 4.5,
        description: "A coastal town known for its golden beaches, water sports, and luxury resorts.",
        attractions: ["Bentota Beach", "River Safari", "Brief Garden"],
        bestTime: "December to March",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 16,
        name: "Colombo",
        slug: "colombo",
        location: "Western Province",
        region: "West",
        interest: "Cultural",
        image: "/images/lotus-tower.png",
        rating: 4.3,
        description: "The bustling commercial capital of Sri Lanka, blending modern skyscrapers with colonial architecture.",
        attractions: ["Lotus Tower", "Galle Face Green", "National Museum"],
        bestTime: "January to March",
        price: "$0",
        category: "City"
    },
    {
        id: 17,
        name: "Kalpitiya",
        slug: "kalpitiya",
        location: "Puttalam",
        region: "North West",
        interest: "Nature",
        image: "/images/cimage.jpg",
        rating: 4.7,
        description: "A coastal town known for its dolphin watching and world-class kitesurfing spots.",
        attractions: ["Dolphin Watching", "Kitesurfing", "Dutch Fort"],
        bestTime: "November to April",
        price: "$40",
        category: "Adventure"
    },
    {
        id: 18,
        name: "Pasikudah",
        slug: "pasikudah",
        location: "Batticaloa",
        region: "East",
        interest: "Beaches",
        image: "/images/beach.jpg",
        rating: 4.8,
        description: "Famous for its shallow turquoise bay, allowing you to walk kilometers into the sea.",
        attractions: [" Pasikudah Bay", "Coral Reefs", "Water Sports"],
        bestTime: "May to September",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 19,
        name: "Adam's Peak",
        slug: "adams-peak",
        location: "Ratnapura District",
        region: "Central",
        interest: "Cultural",
        image: "/images/moody-mountains.jpg",
        rating: 4.9,
        description: "A sacred mountain climb known for the 'sacred footprint' and breathtaking sunrise views.",
        attractions: ["Cloud Forest Hike", "Pilgrimage Route", "Sunrise Peak"],
        bestTime: "December to May",
        price: "$0",
        category: "Mountains"
    },
    {
        id: 20,
        name: "Udawalawe",
        slug: "udawalawe",
        location: "Ratnapura",
        region: "South",
        interest: "Wildlife",
        image: "/images/baby-elephant.jpg",
        rating: 4.6,
        description: "The best place in Sri Lanka to see wild elephants in their thousands throughout the year.",
        attractions: ["Elephant Safari", "Udawalawe Dam", "Elephant Transit Home"],
        bestTime: "Year-round",
        price: "$20",
        category: "Safari"
    },
    {
        id: 21,
        name: "Polhena Beach",
        slug: "polhena",
        location: "Matara",
        region: "South",
        interest: "Beaches",
        image: "/images/mirissa-beach.jpg",
        rating: 4.5,
        description: "A calm beach protected by a coral reef, ideal for swimming and snorkeling with sea turtles.",
        attractions: ["Snorkeling", "Turtle Watching", "Calm Waters"],
        bestTime: "December to April",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 22,
        name: "Nilaveli",
        slug: "nilaveli",
        location: "Trincomalee",
        region: "East",
        interest: "Beaches",
        image: "/images/beach.jpg",
        rating: 4.9,
        description: "One of the finest beaches in the world, with pure white sands and crystal clear waters.",
        attractions: ["Pigeon Island", "Boat Rides", "Sunbathing"],
        bestTime: "May to September",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 23,
        name: "Knuckles Range",
        slug: "knuckles",
        location: "Matale/Kandy",
        region: "Central",
        interest: "Nature",
        image: "/images/moody-mountains.jpg",
        rating: 4.8,
        description: "A UNESCO World Heritage site offering some of the most challenging and scenic hiking trails.",
        attractions: ["Mini World's End", "Waterfall Trekking", "Camping"],
        bestTime: "June to August",
        price: "$10",
        category: "Mountains"
    },
    {
        id: 24,
        name: "Bundala National Park",
        slug: "bundala",
        location: "Hambantota",
        region: "South",
        interest: "Wildlife",
        image: "/images/yala.jpg",
        rating: 4.4,
        description: "An important wetland sanctuary home to thousands of migratory birds and crocodiles.",
        attractions: ["Bird Watching", "Jeep Safari", "Lakeside Views"],
        bestTime: "September to March",
        price: "$20",
        category: "Wildlife"
    },
    {
        id: 25,
        name: "Wilpattu",
        slug: "wilpattu",
        location: "Anuradhapura",
        region: "North West",
        interest: "Wildlife",
        image: "/images/yala.jpg",
        rating: 4.7,
        description: "The largest and oldest national park in Sri Lanka, famous for its numerous 'Villus' (natural lakes).",
        attractions: ["Leopard Safari", "Sloth Bear Spotting", "Lakeside Camping"],
        bestTime: "February to October",
        price: "$25",
        category: "Wildlife"
    },
    {
        id: 26,
        name: "Tangalle",
        slug: "tangalle",
        location: "Hambantota",
        region: "South",
        interest: "Beaches",
        image: "/images/mirissa-beach.jpg",
        rating: 4.6,
        description: "Slow-paced coastal town with beautiful secluded coves and a relaxing atmosphere.",
        attractions: ["Goyambokka Beach", "Silent Beach", "Turtle Hatchery"],
        bestTime: "December to April",
        price: "$0",
        category: "Coasts"
    },
    {
        id: 27,
        name: "Haputale",
        slug: "haputale",
        location: "Badulla",
        region: "Central",
        interest: "Nature",
        image: "/images/nature.jpg",
        rating: 4.7,
        description: "A misty town sitting on the edge of the hill country with dramatic views of the southern plains.",
        attractions: ["Lipton's Seat", "Adisham Bungalow", "Diyaluma Falls"],
        bestTime: "January to March",
        price: "$0",
        category: "Mountains"
    },
    {
        id: 28,
        name: "Mannar Island",
        slug: "mannar",
        location: "Mannar",
        region: "North",
        interest: "Nature",
        image: "/images/hawaii-beach.jpg",
        rating: 4.2,
        description: "Known for its baobab trees, flamingos, and the historic Adam's Bridge leading to India.",
        attractions: ["Baobab Trees", "Flamingo Watching", "Adam's Bridge"],
        bestTime: "November to February",
        price: "$0",
        category: "Nature"
    },
    {
        id: 29,
        name: "Kitulgala",
        slug: "kitulgala",
        location: "Kegalle District",
        region: "Central",
        interest: "Nature",
        image: "/images/nature.jpg",
        rating: 4.5,
        description: "The adventure capital of Sri Lanka, famous for white-water rafting on the Kelani River.",
        attractions: ["White Water Rafting", "Waterfall Abseiling", "Caving"],
        bestTime: "February to April",
        price: "$35",
        category: "Adventure"
    },
    {
        id: 30,
        name: "Batticaloa",
        slug: "batticaloa",
        location: "Eastern Province",
        region: "East",
        interest: "Cultural",
        image: "/images/beach.jpg",
        rating: 4.3,
        description: "Known for its singing fish, historic fort, and beautiful lagoons.",
        attractions: ["Batticaloa Fort", "Kallady Beach", "Lagoon Boat Rides"],
        bestTime: "May to September",
        price: "$0",
        category: "Heritage"
    }
];

export const experiences = [
    {
        id: 1,
        title: "Scenic Kandy to Ella Train",
        category: "Adventure",
        location: "Central Highlands",
        image: "/images/train.jpg",
        price: "$15",
        duration: "7 Hours",
        difficulty: "Easy",
        bestTime: "Year-round",
        description: "The world-famous train journey through misty tea plantations, pine forests, and cascading waterfalls.",
        highlights: ["Demodara Nine Arch Bridge", "Tea Estate Views", "Local Food Vendors"]
    },
    {
        id: 2,
        title: "Traditional Cooking Class",
        category: "Culinary",
        location: "Kandy / Ella",
        image: "/images/cooking.jpg",
        price: "$25",
        duration: "3 Hours",
        difficulty: "Easy",
        bestTime: "Year-round",
        description: "Learn the secrets of Sri Lankan spices. Pick fresh ingredients from a local garden and cook a classic rice and curry meal.",
        highlights: ["Spice Education", "Clay Pot Cooking", "Family-style Dining"]
    },
    {
        id: 3,
        title: "Leopard Safari in Yala",
        category: "Wildlife",
        location: "Yala National Park",
        image: "/images/yala.jpg",
        price: "$85",
        duration: "Half Day",
        difficulty: "Moderate",
        bestTime: "Feb – June",
        description: "A thrilling jeep safari in the park with the highest density of leopards in the world.",
        highlights: ["Leopard Spotting", "Elephant Encounters", "Rugged Terrain"]
    },
    {
        id: 4,
        title: "Surfing in Arugam Bay",
        category: "Adventure",
        location: "East Coast",
        image: "/images/two.jpg",
        price: "$40",
        duration: "2 Hours",
        difficulty: "Moderate",
        bestTime: "May – Sept",
        description: "Ride the epic waves of one of the world's top surfing destinations. Perfect for both beginners and pros.",
        highlights: ["Main Point Break", "Sunset Surf", "Chilled Vibes"]
    },
    {
        id: 5,
        title: "Ayurvedic Wellness Retreat",
        category: "Wellness",
        location: "South Coast",
        image: "/images/spa.jpg",
        price: "$120",
        duration: "Full Day",
        difficulty: "Relaxing",
        bestTime: "Dec – April",
        description: "Detoxify your body and mind with ancient Ayurvedic oil massages and herbal steam baths.",
        highlights: ["Herbal Remedies", "Meditation Sessions", "Holistic Healing"]
    },
    {
        id: 6,
        title: "Sigiriya Ballooning",
        category: "Adventure",
        location: "Dambulla",
        image: "/images/sigiriya.jpg",
        price: "$210",
        duration: "1.5 Hours",
        difficulty: "Easy",
        bestTime: "Nov – April",
        description: "Float over the majestic Sigiriya Rock at dawn, witnessing the island's greens from a unique perspective.",
        highlights: ["Aerial Views", "Sunrise Toast", "Bird's eye sigiriya"]
    },
    {
        id: 7,
        title: "Whale Watching",
        category: "Wildlife",
        location: "Mirissa",
        image: "/images/mirissa-clear.jpg",
        price: "$50",
        duration: "4 Hours",
        difficulty: "Moderate",
        bestTime: "Nov – April",
        description: "Embark on a maritime adventure to see blue whales, sperm whales, and dolphins in their natural habitat.",
        highlights: ["Blue Whales", "Eco-friendly Boats", "Ocean Breeze"]
    },
    {
        id: 8,
        title: "Kandy Esala Perahera",
        category: "Festivals",
        location: "Kandy",
        image: "/images/kandy.jpg",
        price: "$0",
        duration: "Evenings",
        difficulty: "Easy",
        bestTime: "July / August",
        description: "Experience Asia's most grand festival featuring decorated elephants, traditional dancers, and fire-breathers.",
        highlights: ["Sacred Relic Procession", "Cultural Dancers", "Historic Tradition"]
    },
    {
        id: 9,
        title: "Hiking Ella Rock",
        category: "Adventure",
        location: "Ella",
        image: "/images/EllaRock.png",
        price: "$10",
        duration: "4 Hours",
        difficulty: "Hard",
        bestTime: "Year-round",
        description: "A challenging yet rewarding hike offering the most iconic panoramic views of the hill country.",
        highlights: ["Peak Views", "Railway Trekking", "Pine Forests"]
    },
    {
        id: 10,
        title: "Galle Fort Walk",
        category: "Heritage",
        location: "Galle",
        image: "/images/galle.jpg",
        price: "$0",
        duration: "2 Hours",
        difficulty: "Easy",
        bestTime: "December - April",
        description: "Walk along the historic ramparts of the 17th-century Dutch fort, a UNESCO World Heritage site.",
        highlights: ["Lighthouse Views", "Colonial Architecture", "Sunset Ramparts"]
    },
    {
        id: 11,
        title: "Mirissa Sunset Bliss",
        category: "Leisure",
        location: "Mirissa",
        image: "/images/mirissa-beach.jpg",
        price: "$0",
        duration: "Evening",
        difficulty: "Easy",
        bestTime: "November - April",
        description: "Relax on the golden sands of Mirissa as the sun dips below the horizon in a blaze of colors.",
        highlights: ["Coconut Tree Hill", "Sunset Cocktails", "Beach Vibe"]
    },
    {
        id: 12,
        title: "Highland Tea Journey",
        category: "Heritage",
        location: "Nuwara Eliya",
        image: "/images/tea.png",
        price: "$15",
        duration: "3 Hours",
        difficulty: "Easy",
        bestTime: "Year-round",
        description: "Visit a working tea factory and learn the art of picking and processing Ceylon's finest tea.",
        highlights: ["Tea Tasting", "Estate Walks", "Factory Tour"]
    }
];
